- name: 设置集群参数
  shell: "{{ software_dir }}/k8s/kubectl config set-cluster kubernetes \
        --certificate-authority={{ base_dir }}/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }} \
        --kubeconfig={{ base_dir }}/ssl/kube.config"

- name: 设置客户端认证参数
  shell: "{{ software_dir }}/k8s/kubectl config set-credentials admin \
        --client-certificate={{ base_dir }}/ssl/admin.pem \
        --embed-certs=true \
        --client-key={{ base_dir }}/ssl/admin-key.pem \
        --kubeconfig={{ base_dir }}/ssl/kube.config"

- name: 设置上下文参数
  shell: "{{ software_dir }}/k8s/kubectl config set-context kubernetes \
        --cluster=kubernetes --user=admin \
        --kubeconfig={{ base_dir }}/ssl/kube.config"

- name: 选择默认上下文
  shell: "{{ software_dir }}/k8s/kubectl config use-context kubernetes --kubeconfig={{ base_dir }}/ssl/kube.config"
  

