- name: 设置集群参数
  shell: "{{ software_dir }}/k8s/kubectl config set-cluster kubernetes \
        --certificate-authority={{ base_dir }}/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }} \
        --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig"

- name: 设置认证参数
  shell: "{{ software_dir }}/k8s/kubectl config set-credentials system:kube-controller-manager \
        --client-certificate={{ base_dir }}/ssl/kube-controller-manager.pem \
        --client-key={{ base_dir }}/ssl/kube-controller-manager-key.pem \
        --embed-certs=true \
        --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig"

- name: 设置上下文参数
  shell: "{{ software_dir }}/k8s/kubectl config set-context default \
        --cluster=kubernetes \
        --user=system:kube-controller-manager \
        --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig"

- name: 选择默认上下文
  shell: "{{ software_dir }}/k8s/kubectl config use-context default \
   --kubeconfig={{ base_dir }}/ssl/kube-controller-manager.kubeconfig"
