- name: 设置集群参数
  shell: "{{ software_dir }}/k8s/kubectl config set-cluster kubernetes \
        --certificate-authority={{ base_dir }}/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }} \
        --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig"

- name: 设置客户端认证参数
  shell: "{{ software_dir }}/k8s/kubectl config set-credentials kube-proxy \
        --client-certificate={{ base_dir }}/ssl/kube-proxy.pem \
        --client-key={{ base_dir }}/ssl/kube-proxy-key.pem \
        --embed-certs=true \
        --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig"

- name: 设置上下文参数
  shell: "{{ software_dir }}/k8s/kubectl config set-context default \
        --cluster=kubernetes \
        --user=kube-proxy \
        --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig"

- name: 选择默认上下文
  shell: "{{ software_dir }}/k8s/kubectl config use-context default \
   --kubeconfig={{ base_dir }}/ssl/kube-proxy.kubeconfig"
