---
- name: 0.系统初始化
  gather_facts: true
  hosts: 
    - k8s
    - etcd
  roles:
    - common
  tags: common 

- name: 1.自签证书 
  gather_facts: false
  hosts: localhost 
  roles:
    - deploy
  tags: deploy
  
- name: 2.部署ETCD集群
  gather_facts: false
  hosts: etcd
  roles:
    - etcd
  tags: etcd

- name: 3.部署K8S Master
  gather_facts: false
  hosts: master
  roles:
    - master
  tags: master

- name: 4.部署slb
  gather_facts: false
  hosts: lb
  roles:
    - { role: ha, when: "groups['master']|length > 1" }
  tags: ha

- name: 5.部署flannel
  gather_facts: false
  hosts: k8s 
  roles:
    - flannel 
  tags: flannel

- name: 6.部署Docker
  gather_facts: false
  hosts: k8s 
  roles:
    - docker 
  tags: docker

- name: 7.部署K8S Node
  gather_facts: false
  hosts: k8s
  roles:
    - node
  tags: node

- name: 8.部署插件
  gather_facts: false
  hosts: master[0]
  roles:
    - addons
  tags: addons
